import 'package:flutter/material.dart';

Color green = const Color(0xFF029933);

List<String> themes = const [
  "Tawhid",
  "Prière",
  "Ramadan",
  "Zakat",
  "Hajj",
  "Le Coran",
  "La Sunna",
  "Messagers et Prophètes",
  "Sectes",
  "Les Compagnons",
  "Les Savants",
  "Innovation",
  "La mort",
  "La tombe",
  "Le jour dernier",
  "Les 4 Imams",
  "Les Anges",
  "Les Djinns",
  "Les gens du livre",
  "Les noms d’Allah",
  "Fiqh",
  "Les Madhabs",
  "Les femmes",
  "Le voyage",
  "Signe fin des temps",
  "Adkars",
];

List<String> scholars = const [
  "Cheikh Abdesamad Karoum / الشيخ عبد الصمد كروم",
  "Cheikh Abderrazak Al Badr / الشيخ عبد الرزاق البدر",
  "Cheikh Abdelkarim Al Khoudayr / الشيخ عبد الكريم الخضير",
  "Cheikh Abdelmadjid Jumu’a / الشيخ عبد المجيد جمعة",
  "Cheikh Abdelmouhsin Al Abbad Al Badr / الشيخ عبد المحسن العباد البدر",
  "Cheikh Abdellah Al Idrissi / شيخ عبدالله الدراسي",
  "Cheikh Abdellah Al Qussayir / شيخ عبد الله القصير",
  "Cheikh Abdallah Al Ghoudayan / الشيخ عبد الله الغديان",
  "Cheikh Abderahman As-Sa’di / الشيخ عبد الرحمن السعدي",
  "Cheikh Abderahman Mouhyiddine / الشيخ عبد الرحمن محي الدين",
  "Cheikh Abdesalam Ibn Barjas / الشيخ عبد السلام بن برجس",
  "Cheikh Abdesalam Chouway’ir / الشيخ عبد السلام الشويعر",
  "Cheikh Ahmad Bazmoul / الشيخ أحمد بزمول",
  "Cheikh Ahmad Najmi / الشيخ أحمد النجمي",
  "Cheikh Al Albani / الشيخ الألباني",
  "Cheikh Al Uthaymin / شيخ العثيمين",
  "Cheikh Ali Cheikh / شيخ علي شيخ",
  "Cheikh Ali Ramli / الشيخ علي الرملي",
  "Cheikh As Souhaymi / شيخ السحيمي",
  "Cheikh Aziz bin Farhan Al Anizi / الشيخ عزيز بن فرحان العنزي",
  "Cheikh Faleh Mundakar / شيخ فلح مندكار",
  "Cheikh Faqiri / شيخ فقيري",
  "Cheikh Ferkous / الشيخ فركوس",
  "Cheikh Foued Ibn Saoud Al Amri / الشيخ فؤاد بن سعود العمري",
  "Cheikh Hassan Ibn Abdelwahhab Al Bana / الشيخ حسن بن عبد الوهاب البنا",
  "Cheikh Ibrahim Al Mouhaymid / الشيخ إبراهيم المحيميد",
  "Cheikh Ibn Baz / الشيخ ابن باز",
  "Cheikh Mouqbil Al Wadi’i / الشيخ مقبل الوادعي",
  "Cheikh Muhammad Al Aqil / الشيخ محمد العقيل",
  "Cheikh Muhammad Al Fifi / الشيخ محمد الفيفي",
  "Cheikh Muhammad Al Jami / الشيخ محمد الجامي",
  "Cheikh Muhammad Al Shanqiti / الشيخ محمد الشنقيطي",
  "Cheikh Muhammad Al Wussabi / الشيخ محمد الوصابي",
  "Cheikh Muhammad Bazmoul / الشيخ محمد بزمول",
  "Cheikh Muhammad Ibn Hadi Al Madkhali / الشيخ محمد بن هادي المدخلي",
  "Cheikh Muhammad Ibn Ibrahim / الشيخ محمد بن إبراهيم",
  "Cheikh Muhammad Shawkani / الشيخ محمد الشوكاني",
  "Cheikh Mohamed Ghaïth / شيخ محمد غيث",
  "Cheikh Rabi’ Al Madkhali / الشيخ ربيع المدخلي",
  "Cheikh Ramzan Al Hadjiri / الشيخ رمضان الحجيري",
  "Cheikh Raslan / شيخ عسلان",
  "Cheikh Rouhayli (Souleyman) / شيخ سليمان الرحيلي",
  "Cheikh Saad Ibn Nasser Ash Shathry / الشيخ سعد بن ناصر الشثرى",
  "Cheikh Salih Al Fawzan / الشيخ صالح الفوزان",
  "Cheikh Salih Al Louhaydan / الشيخ صالح اللحيدان",
  "Cheikh Salih Al Osaymi / الشيخ صالح العصيمي",
  "Cheikh Salih Al Shaykh / الشيخ صالح الشيخ",
  "Cheikh Salih Ali Cheikh / شيخ صالح علي شيخ",
  "Cheikh Salih Souhaymi / الشيخ صالح السحيمي",
  "Cheikh Salih Sindi / شيخ صالح سندي",
  "Cheikh Salmane At Tawil / شيخ سلمان الطويلة",
  "Cheikh Tal’at Zahran / الشيخ طلعت زهران",
  "Cheikh Ussamah Ibn Saoud Al Amri / الشيخ أسامة بن سعود العمري",
  "Cheikh Wassiyullah Al Abbas / الشيخ وصي الله عباس",
  "Cheikh Zayd Al Madkhali / الشيخ زيد المدخلي"
];
